version: v1
services:
  service0:
    image: gcr.io/google_containers/pause:3.0
  service1:
    image: gcr.io/google_containers/pause:3.0
    depends_on:
      - service0
  service2:
    image: gcr.io/google_containers/pause:3.0
    depends_on:
      - service0
  service3:
    image: gcr.io/google_containers/pause:3.0
    depends_on:
      - service0
      - service1
tasks:
  task0:
    image: ubuntu:latest
    command: [ "echo", "huhu from task0" ]
  task1:
    image: ubuntu:latest
    command: [ "bash", "-c", "for i in $(seq 1 5); do echo \"huhu #$i from task1\"; sleep 1; done" ]
    depends_on:
      - task0
  task2:
    image: ubuntu:latest
    command: [ "echo", "huhu from task2" ]
    depends_on:
      - task1
