version: v1
services:
  service0:
    image: gcr.io/google_containers/pause:3.0
  service1:
    image: gcr.io/google_containers/pause:3.0
    depends_on:
      - service0
tasks:
  task0:
    image: ubuntu:latest
    command: [ "echo", "huhu" ]
  task1:
    image: ubuntu:latest
    command: [ "echo", "huhu" ]
    depends_on:
      - task0
